[env:ambiente-03]
extends = env
board = esp32dev
board_build.partitions = default_4MB.csv
build_src_filter = ${env.build_src_filter} +<../boards/ambiente-03/>

build_flags = 
    ${env.build_flags}
    -Dboards/ambiente-03
    -DDEVICE_NAME="\"Marauder-Mini-Full-ESP32\""

    ; --- PINAGEM OBRIGATÓRIA (Nomes curtos para as bibliotecas) ---
    -DSCK=18
    -DMOSI=23
    -DMISO=19
    -DSS=5
    -DSDA=21
    -DSCL=22

    ; --- Definições de periféricos ---
    -DDTFT_CS=15
    -DDTFT_DC=2
    -DDTFT_RST=4
    -DDTFT_BL=32
    -DSDCARD_CS=14
    
    -DNRF24_CE=25
    -DNRF24_CS=26
    
    -DCC1101_GDO0=27
    -DCC1101_CS=22
    
    -DIR_TX=33
    -DIR_RX=32
    
    -DGPS_TX=17
    -DGPS_RX=16
    
    -DJOY_VRX=34
    -DJOY_VRY=35
    -DJOY_SW=36
    
