[env:ambiente-03]
extends = env
board = esp32dev
board_build.partitions = default_4MB.csv
build_src_filter = ${env.build_src_filter} +<../boards/ambiente-03/>

build_flags = 
    ${env.build_flags}
    -Dboards/ambiente-03
    -DDEVICE_NAME="\"Marauder-Mini-Full-ESP32\""

    ; SPI Compartilhado (Pinos Padrão VSPI do ESP32 Clássico)
    -DSPI_SCK_PIN=18
    -DSPI_MOSI_PIN=23
    -DSPI_MISO_PIN=19
    -DSPI_SS_PIN=5

    ; Display 1.8" ST7735 128x160
    -DHAS_SCREEN=1
    -DST7735_DRIVER=1
    -DST7735_GREENTAB160x128=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DDTFT_MISO=SPI_MISO_PIN
    -DDTFT_MOSI=SPI_MOSI_PIN
    -DDTFT_SCK=SPI_SCK_PIN
    -DDTFT_CS=15
    -DDTFT_DC=2
    -DDTFT_RST=4
    -DDTFT_BL=32

    ; SD Card (SPI)
    -DSDCARD_CS=14

    ; NRF24L01+PA
    -DNRF24_CE_PIN=25
    -DNRF24_SS_PIN=26

    ; CC1101
    -DCC1101_GDO0_PIN=27
    -DCC1101_SS_PIN=22

    ; Infravermelho (IR)
    -DIR_TX_PIN=33
    -DIR_RX_PIN=32

    ; GPS (UART2)
    -DSERIAL_TX=17
    -DSERIAL_RX=16
    -DGPS_SERIAL_TX=SERIAL_TX
    -DGPS_SERIAL_RX=SERIAL_RX

    ; PN532 (I2C)
    -DSYS_I2C_SDA=21
    -DSYS_I2C_SCL=22

    ; Joystick KY-023 (Pinos Analógicos ADC1 e Digital)
    -DJOY_VRX_PIN=34
    -DJOY_VRY_PIN=35
    -DJOY_SW_PIN=36

lib_deps = 
    ${env.lib_deps}
    
