; Ambiente 03 - ESP32 DevKit 30-pin + Display 1.8" 128x160 (Serial) + modules
[env:ambiente-03]
extends = env
board = esp32dev
board_build.partitions = custom_8Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/ambiente-03>
build_flags =
    ${env.build_flags}
    -Iboards/ambiente-03
    -DDEVICE_NAME='"Ambiente-03 ESP32-DevKit 1.8 TFT"'

    ; SPI (common)
    -DSPI_SCK_PIN=18
    -DSPI_MOSI_PIN=23
    -DSPI_MISO_PIN=19
    -DSPI_SS_PIN=5

    ; Display 1.8" 128x160
    -DHAS_SCREEN=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=4
    -DTFT_BL=21

    ; SD Card
    -DSDCARD_CS=4

    ; NRF24
    -DNRF24_CE_PIN=25
    -DNRF24_SS_PIN=SPI_SS_PIN

    ; CC1101
    -DCC1101_GDO0_PIN=26
    -DCC1101_SS_PIN=21

    ; IR
    -DIR_TX_PIN=27
    -DIR_RX_PIN=13

    ; GPS (use a spare UART)
    -DGPS_SERIAL_TX=16
    -DGPS_SERIAL_RX=17

    ; PN532 (optional, I2C)
    -DSYS_I2C_SDA=21
    -DSYS_I2C_SCL=22

    ; Joystick
    -DJOY_VRX_PIN=34
    -DJOY_VRY_PIN=35
    -DJOY_SW_PIN=32

lib_deps =
    ${env.lib_deps}
