; Ambiente 01 - ESP32 S3N16R8 + Display 1.8" 128x160 (SPI serial) + SD
[env:ambiente-01]
extends = env
board = esp32-s3-devkitc-1
board_build.partitions = custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +../boards/ambiente-01
extra_scripts = patch_spi.py
build_flags = 
    ${env.build_flags}
    -Iboards/ambiente-01
    -DDEVICE_NAME="'Ambiente-01 ESP32-S3N16R8 1.8 TFT'"
    -DBOARD_HAS_PSRAM
    
    ; SPI (shared) - Sem o -DSS global para não conflitar com libopus
    -DSCK=18
    -DMOSI=23
    -DMISO=19
    -DSPI_SCK_PIN=18
    -DSPI_MOSI_PIN=23
    -DSPI_MISO_PIN=19
    -DSPI_SS_PIN=5

    ; I2C (Wire)
    -DSDA=8
    -DSCL=9

    ; Display 1.8" 128x160
    -DHAS_SCREEN=1
    -DTFT_WIDTH=128
    -DTFT_HEIGHT=160
    -DTFT_MISO=SPI_MISO_PIN
    -DTFT_MOSI=SPI_MOSI_PIN
    -DTFT_SCK=SPI_SCK_PIN
    -DTFT_CS=17
    -DTFT_DC=16
    -DTFT_RST=15
    -DTFT_BL=14

    ; Touch controller (XPT2046 or similar)
    -DTOUCH_CS=33
    -DTOUCH_IRQ=-1

    ; SD card (on SPI)
    -DSDCARD_CS=4
    -DSDCARD_SCK=SPI_SCK_PIN
    -DSDCARD_MISO=SPI_MISO_PIN
    -DSDCARD_MOSI=SPI_MOSI_PIN
    
