; Ambiente 04 - ESP32 DevKit 30-pin + ST7789 240x240 (7 pinos, no CS) + 2x NRF24 + CC1101 + PN532 optional
[env:ambiente-04]
extends = env
board = esp32dev
board_build.partitions = custom_8Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/ambiente-04>
build_flags =
    ${env.build_flags}
    -Iboards/ambiente-04
    -DDEVICE_NAME='"Ambiente-04 ESP32-DevKit ST7789 240x240"'

    ; SPI (shared)
    -DSPI_SCK_PIN=18
    -DSPI_MOSI_PIN=23
    -DSPI_MISO_PIN=19
    -DSPI_SS_PIN=5

    ; ST7789 240x240 with no CS (CS = -1)
    -DHAS_SCREEN=1
    -DST7789_NO_CS=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_CS=-1
    -DTFT_DC=21
    -DTFT_RST=22
    -DTFT_BL=19

    ; SD Card (if used)
    -DSDCARD_CS=4

    ; Two NRF24 modules (two CS/CE lines required)
    -DNRF24_1_CE_PIN=25
    -DNRF24_1_SS_PIN=5
    -DNRF24_2_CE_PIN=26
    -DNRF24_2_SS_PIN=27

    ; CC1101 (single)
    -DCC1101_GDO0_PIN=32
    -DCC1101_SS_PIN=33

    ; IR
    -DIR_TX_PIN=13
    -DIR_RX_PIN=14

    ; PN532 (optional, prepare pins)
    -DSYS_I2C_SDA=21
    -DSYS_I2C_SCL=22

    ; Joystick
    -DJOY_VRX_PIN=34
    -DJOY_VRY_PIN=35
    -DJOY_SW_PIN=32

lib_deps =
    ${env.lib_deps}
