[env:Marauder-Mini]
board = esp32dev
board_build.partitions = custom_4Mb_full.csv
build_src_filter = ${env.build_src_filter} +<../boards/marauder-mini>
build_flags =
    ${env.build_flags}
    ${env_4mb.build_flags}
    -Iboards/marauder-mini
    -D MARAUDER_MINI
    -D USER_SETUP_LOADED=1
    -D ST7789_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_BL=32
    -D TFT_CS=-1
    -D TFT_DC=16
    -D TFT_RST=5
    -D TFT_BACKLIGHT_ON=HIGH
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000
    -D TOUCH_CS=-1
    -D DEVICE_NAME='"Marauder Mini ST7789"'
lib_deps =
    ${env.lib_deps}
lib_ignore =
    ${env_4mb.lib_ignore}
    
