[env:esp32-s3-devkitc-1]
extends = env:esp32-s3-devkitc-1
board = esp32-s3-devkitc-1
board_build.partitions = custom_16Mb.csv
board_upload.maximum_size = 16777216

build_src_filter = +<src/*> +<../boards/Marauder-Radio/*>

build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -D BOARD_HAS_PSRAM=1
    -Iboards/Marauder-Radio
    -DDEVICE_NAME='"Marauder Radio - Teste Tela"'

    ; --- SPI do Display ---
    -DSCK=18
    -DMOSI=23
    -DMISO=19
    -DSS=5
    -DSPI_SCK_PIN=18
    -DSPI_MOSI_PIN=23
    -DSPI_MISO_PIN=19
    -DSPI_SS_PIN=5

    ; --- Display 2.8 ST7789 240x320 ---
    -DST7789_DRIVER=1
    -DHAS_SCREEN=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DUSER_SETUP_LOADED=1
    -DSMOOTH_FONT=1
    -DCGRAM_OFFSET=1
    -DTFT_MISO=SPI_MISO_PIN
    -DTFT_MOSI=SPI_MOSI_PIN
    -DTFT_SCK=SPI_SCK_PIN
    -DTFT_CS=17
    -DTFT_DC=16
    -DTFT_RST=15
    -DTFT_BL=14

lib_deps =
    ${env.lib_deps}
