[env:Marauder-pro]
extends = env:esp32-s3-devkitc-1
board = esp32-s3-devkitc-1
board_build.partitions = custom_16Mb.csv
board_upload.maximum_size = 16777216

build_src_filter = +<src/*>

build_flags =
    ${env:esp32-s3-devkitc-1.build_flags}
    -D BOARD_HAS_PSRAM=1
    -Iboards/Marauder-pro
    -DDEVICE_NAME='"Marauder Pro"'

    ; --- Driver Principal da Tela ---
    -DILI9341_2_DRIVER=1
    -DUSER_SETUP_LOADED=1
    -DSMOOTH_FONT=1

    ; --- Ativação de Protocolos de Rádio ---
    -DUSE_CC1101_VIA_SPI=1
    -DUSE_NRF24_VIA_SPI=1

lib_deps =
	${env.lib_deps}

lib_ignore =
	${env_16mb.lib_ignore}
  
