; Ambiente 02 - ESP32 S3N16R8 + Display 2.8" ST7789V 240x320 (SPI + Touch)
[env:ambiente-02]
extends = env
board = esp32-s3-devkitc-1
board_build.partitions = custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/ambiente-02>
build_flags =
    ${env.build_flags}
    -Iboards/ambiente-02
    -DDEVICE_NAME='"Ambiente-02 ESP32-S3N16R8 2.8 ST7789"'

    ; SPI Globais exigidas pelo framework do ESP32
    -DSCK=12
    -DMOSI=11
    -DMISO=10
    -DSS=5

    ; SPI Específicas do ambiente
    -DSPI_SCK_PIN=12
    -DSPI_MOSI_PIN=11
    -DSPI_MISO_PIN=10
    -DSPI_SS_PIN=5

    ; ST7789 240x320 display + Touch controller
    -DHAS_SCREEN=1
    -DHAS_TOUCH=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DUSER_SETUP_LOADED=1
    -DSMOOTH_FONT=1
    -DUSING_JOYSTICK=1
    -DGEIST_ROTARY_ENCODER=0  
    -DTFT_MISO=SPI_MISO_PIN
    -DTFT_MOSI=SPI_MOSI_PIN
    -DTFT_SCK=SPI_SCK_PIN
    -DTFT_CS=17
    -DTFT_DC=16
    -DTFT_RST=15
    -DTFT_BL=14 
    -DTOUCH_CS=41
    -DTOUCH_IRQ=-1
    -DCGRAM_OFFSET=1

    ; --- I2C (Wire) / PN532 ---
    -DSDA=8
    -DSCL=9
    -DSYS_I2C_SDA=8
    -DSYS_I2C_SCL=9

    ; --- BadUSB Serial Pins ---
    -DBAD_RX=44
    -DBAD_TX=43
    
    ; --- Cartão SD ---
    -DSDCARD_CS=4
    -DSDCARD_SCK=SPI_SCK_PIN
    -DSDCARD_MISO=SPI_MISO_PIN
    -DSDCARD_MOSI=SPI_MOSI_PIN

    ; --- Joystick / Botões ---
    -DJOY_VRX=1
    -DJOY_VRY=2
    -DJOY_SW=6
    -DJOY_VRX_PIN=1
    -DJOY_VRY_PIN=2
    -DJOY_SW_PIN=6

    ; NRF24
    -DNRF24_CE_PIN=25
    -DNRF24_SS_PIN=SPI_SS_PIN

    ; CC1101
    -DCC1101_GDO0_PIN=26
    -DCC1101_SS_PIN=22

    ; IR
    -DIR_TX_PIN=27
    -DIR_RX_PIN=33

    ; GPS
    -DSERIAL_TX=39
    -DSERIAL_RX=40
    -DGPS_SERIAL_TX=SERIAL_TX
    -DGPS_SERIAL_RX=SERIAL_RX

lib_deps =
    ${env.lib_deps}
    
