[env:ambiente-02]
extends = env
board = esp32-s3-devkitc-1
board_build.partitions = custom_16Mb.csv

lib_ignore =
    ESP8266Audio
    ESP8266SAM
    ESP32-audioI2S
    FastLED
    lib2e3
    ESP Chameleon Ultra
    Chameleon
   
build_flags =
    ${env.build_flags}
    -Iboards/ambiente-02
    -DDEVICE_NAME="\"Marauder-Lean-S3\""
    -DBOARD_HAS_PSRAM
   
    -DUSER_SETUP_LOADED=1
    -DSMOOTH_FONT=1
    -DUSING_JOYSTICK=1
    -DGEIST_ROTARY_ENCODER=0

    ; --- Configuração do Display 2.8" (ST7789 240x320) ---
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DCGRAM_OFFSET=1

    ; --- SPI (Pinos seguros S3) ---
    -DSCK=12
    -DMOSI=11
    -DMISO=10
    -DSS=5
    -DSPI_SCK_PIN=12
    -DSPI_MOSI_PIN=11
    -DSPI_MISO_PIN=10
    -DSPI_SS_PIN=5

    ; --- I2C (Wire) ---
    -DSDA=8
    -DSCL=9

    ; --- BadUSB Serial Pins ---
    -DBAD_RX=44
    -DBAD_TX=43

    ; --- Pinos da Tela de 2.8" ---
    -DHAS_SCREEN=1
    -DDTFT_MISO=SPI_MISO_PIN
    -DDTFT_MOSI=SPI_MOSI_PIN
    -DDTFT_SCK=SPI_SCK_PIN
    -DDTFT_CS=17
    -DDTFT_DC=16
    -DDTFT_RST=15
    -DDTFT_BL=14

    ; --- Touch Controller ---
    -DHAS_TOUCH=1
    -DTOUCH_CS=41
    -DTOUCH_IRQ=-1

    ; --- Cartão SD ---
    -DSDCARD_CS=4
    -DSDCARD_SCK=SPI_SCK_PIN
    -DSDCARD_MISO=SPI_MISO_PIN
    -DSDCARD_MOSI=SPI_MOSI_PIN

    ; --- Apenas NRF24 e CC1101 ---
    -DNRF24_CE=13
    -DNRF24_CS=42
    -DCC1101_GDO0=45
    -DCC1101_CS=21

    ; --- Joystick / Botões ---
    -DJOY_VRX=1
    -DJOY_VRY=2
    -DJOY_SW=6
    -DJOY_VRX_PIN=1
    -DJOY_VRY_PIN=2
    -DJOY_SW_PIN=6

lib_deps = 
    ${env.lib_deps}
    
