; Ambiente 02 - ESP32 S3N16R8 + Display 2.8" ST7789V 240x320 (SPI + Touch)
[env:ambiente-02]
extends = env
board = esp32-s3-devkitc-1
board_build.partitions = custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/ambiente-02/>

build_flags = 
    ${env.build_flags}
    -Dboards/ambiente-02
    -DDEVICE_NAME="\"Marauder-Full-ST7789-S3\""
    -DBOARD_HAS_PSRAM

    ; --- PINAGEM OBRIGATÓRIA (Nomes curtos para as bibliotecas no S3) ---
    -DSCK=18
    -DMOSI=11
    -DMISO=10
    -DSS=4
    -DSDA=8
    -DSCL=9

    ; --- Display TFT 2.8" ST7789 240x320 ---
    -DHAS_SCREEN=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DCGRAM_OFFSET=1
    -DDTFT_MISO=MISO
    -DDTFT_MOSI=MOSI
    -DDTFT_SCK=SCK
    -DDTFT_CS=17
    -DDTFT_DC=16
    -DDTFT_RST=15
    -DDTFT_BL=6

    ; --- Touch Controller & SD Card ---
    -DTOUCH_CS=5
    -DSDCARD_CS=4

    ; --- NRF24L01+PA ---
    -DNRF24_CE=13
    -DNRF24_CS=12

    ; --- CC1101 ---
    -DCC1101_GDO0=45
    -DCC1101_CS=21

    ; --- Infravermelho (IR) ---
    -DIR_TX=37
    -DIR_RX=38

    ; --- GPS ---
    -DGPS_TX=40
    -DGPS_RX=39

    ; --- PN532 (I2C) ---
    -DSYS_I2C_SDA=8
    -DSYS_I2C_SCL=9

    ; --- Joystick KY-023 ---
    -DJOY_VRX=1
    -DJOY_VRY=2
    -DJOY_SW=3

lib_deps = 
    ${env.lib_deps}
    
